name: Compile with SourceMod

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ "1.10", "1.11" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "SCRIPTING_PATH=addons/sourcemod/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugins
        run: |
          for file in sun*.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $includePath -i include $file
          done
        working-directory: ${{ env.SCRIPTING_PATH }}

      - name: Create archive
        uses: actions/upload-artifact@v3
        with:
          name: SUN.SM${{ matrix.SM_VERSION }}
          path: ./