name: Compile with SourceMod

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.10", "1.11"]


    steps:
      - uses: actions/checkout@v1

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugin
        run: |
          echo -e "\nCompiling sun.sp..."
          spcomp -E -w234 -O2 -v2 -i addons/sourcemod/scripting/include addons/sourcemod/scripting/sun.sp