name: Compile with SourceMod

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.10", "1.11"]


    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          git fetch --unshallow
          echo "COMMIT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git describe --always --long --dirty)" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile sun.sp
        run: |
          echo -e "\nCompiling sun.sp..."
          spcomp -E -w234 -O2 -v2 -i addons/sourcemod/scripting/include addons/sourcemod/scripting/sun.sp

      - name: Compile sun_discord.sp
        run: |
          echo -e "\nCompiling sun_discord.sp..."
          spcomp -E -w234 -O2 -v2 -i addons/sourcemod/scripting/include addons/sourcemod/scripting/sun_discord.sp

      - name: Create archive
        uses: actions/upload-artifact@v2
        with:
          name: SUN.${{ env.COMMIT }}.${{ env.SHORT_SHA }}.SM${{ matrix.SM_VERSION }}
          path: ./